version: '3'
services:
  consul-server:
    image: consul:1.9.4
    command: consul agent -dev -client 0.0.0.0
    ports:
      - "8500:8500"
      - "8602:8602/udp"

  mongodb:
    image: mongo:4
    container_name: "mancala_mongodb"
    ports:
      - "27017:27017"
    command: --serviceExecutor adaptive

  redisdb:
    restart: always
    container_name: "mancala_redis"
    image: redis
    ports:
      - "6379:6379"

  mancala-api:
    build: ../mancala-api
    links:
      - consul-server
      - zipkin-server
    depends_on:
      - redisdb
      - mongodb
    environment:
      - MANCALA_PIT_STONES=6
      - SPRING_CLOUD_CONSUL_HOST=consul-server
      - SPRING_APPLICATION_NAME=mancala-api
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_REDIS_HOST=redisdb
      - SPRING_REDIS_PORT=6379
      - MANCALA_API_SERVICE_ID= mancala-api
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-server:9411/

  apache:
    build: apache
    links:
      - consul-server
    depends_on:
      - consul-server
    ports:
      - "80:80"

  zipkin-storage:
    image: openzipkin/zipkin-cassandra
    container_name: cassandra
    ports:
      - "9042:9042"

  zipkin-server:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=cassandra3
      - CASSANDRA_ENSURE_SCHEMA=false
      - CASSANDRA_CONTACT_POINTS=cassandra
    depends_on:
      - zipkin-storage

